return {}
-- return {
--   "neovim/nvim-lspconfig",
--   opts = function(_, opts)
--     local yaml = require("lang.yaml")
--     if yaml and yaml.setup then
--       yaml.setup()
--     end
--   end,
-- }
-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       yamlls = {
--         settings = {
--           yaml = {
--             customTags = {
--               "!reference sequence",
--             },
--           },
--         },
--       },
--     },
--   },
-- }
